from pathlib import Path
path = Path("js/uiController.js")
text = path.read_text(encoding="utf-8")
old = "    createContinentBlock(continentName, locations) {\r\n        const wrapper = document.createElement('div');\r\n        wrapper.className = 'continent';\r\n        wrapper.dataset.continent = continentName;\r\n\r\n        const toggleButton = document.createElement('button');\r\n        toggleButton.className = 'continent-toggle';\r\n        toggleButton.innerHTML = `${continentName} <span class=\"location-count\">(${locations.length})</span>`;\r\n\r\n        const content = document.createElement('div');\r\n        content.className = 'continent-content';\r\n        content.style.display = 'none';\r\n\r\n        const continentInfo = {\r\n            name: continentName,\r\n            wrapper,\r\n            toggleButton,\r\n            content,\r\n            isOpen: false\r\n        };\r\n\r\n        toggleButton.addEventListener('click', () => {\r\n            continentInfo.isOpen = !continentInfo.isOpen;\r\n            content.style.display = continentInfo.isOpen ? 'block' : 'none';\r\n        });\r\n\r\n        locations.forEach(location => {\r\n            const entry = this.createLocationEntry(location, continentInfo);\r\n            content.appendChild(entry.element);\r\n            this.entries.push(entry);\r\n        });\r\n\r\n        wrapper.appendChild(toggleButton);\r\n        wrapper.appendChild(content);\r\n        return continentInfo;\r\n    }\r\n\r\n"
new = "    createContinentBlock(continentName, locations) {\r\n        const wrapper = document.createElement('div');\r\n        wrapper.className = 'continent';\r\n        wrapper.dataset.continent = continentName;\r\n\r\n        const toggleButton = document.createElement('button');\r\n        toggleButton.className = 'continent-toggle';\r\n        toggleButton.innerHTML = `${continentName} <span class=\"location-count\">(${locations.length})</span>`;\r\n\r\n        const content = document.createElement('div');\r\n        content.className = 'continent-content';\r\n        content.style.display = 'none';\r\n\r\n        const continentInfo = {\r\n            name: continentName,\r\n            wrapper,\r\n            toggleButton,\r\n            content,\r\n            isOpen: false,\r\n            entries: [],\r\n            pagination: {\r\n                currentPage: this.preferences ? this.preferences.getPagination(continentName) : 0,\r\n                totalPages: 1\r\n            },\r\n            paginationControls: null\r\n        };\r\n\r\n        toggleButton.addEventListener('click', () => {\r\n            continentInfo.isOpen = !continentInfo.isOpen;\r\n            content.style.display = continentInfo.isOpen ? 'block' : 'none';\r\n        });\r\n\r\n        locations.forEach(location => {\r\n            const entry = this.createLocationEntry(location, continentInfo);\r\n            content.appendChild(entry.element);\r\n            this.entries.push(entry);\r\n        });\r\n\r\n        continentInfo.paginationControls = this.createPaginationControls(continentInfo);\r\n        if (continentInfo.paginationControls) {\r\n            content.appendChild(continentInfo.paginationControls.container);\r\n        }\r\n\r\n        wrapper.appendChild(toggleButton);\r\n        wrapper.appendChild(content);\r\n        return continentInfo;\r\n    }\r\n\r\n"
if old not in text:
    raise SystemExit('createContinentBlock block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
